name: macOS C CI

on:
  push:
#    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v3
    - run: git submodule update --init --recursive --remote
    - name: make
      run: make
    - name: python tester
      run: |
        pip3 install -r requirements.txt
        python3 tests/test.py
